controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
# event_index:
#     path: /events
#     controller: App\Controller\EventController::index
